version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: smvlad/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: smvlad/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    image: smvlad/foodgram_gateway
    volumes:
      - static_volume:/staticfiles
      - media_volume:/app/media
    ports:
      - 8000:80
    depends_on:
      - frontend