# Generated by Django 4.2.16 on 2025-01-15 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_alter_favourites_recipe_alter_favourites_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplsit',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_purchase', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='shoplsit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
