# Generated by Django 4.2.16 on 2025-02-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_shoplsit_purchase_alter_shoplsit_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoplsit',
            options={'verbose_name': 'покупки', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
