# Generated by Django 4.2.16 on 2024-11-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
