# Generated by Django 4.2.16 on 2025-01-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_subscribed',
        ),
    ]
